import type { CSSProperties } from "react";
import { GRADIENTS, PAGE_BG, BRAND, FONT_MAIN } from "../../config/theme";

export const styles = {
  page: {
    width: "100%",
    minHeight: "100vh",
    background: PAGE_BG,
    color: BRAND.ink,
    fontFamily: FONT_MAIN,
    boxSizing: "border-box",
    padding: "128px 32px 64px",
  },
  hero: {
    textAlign: "center",
    marginBottom: 40,
  },
  heroTitle: {
    margin: 0,
    fontSize: 48,
    fontWeight: 900,
    letterSpacing: 2,
    background: GRADIENTS.primary,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  content: {
    maxWidth: 1280,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "20px 28px",
    borderRadius: 20,
    background: "rgba(255,255,255,0.86)",
    border: `1px solid ${BRAND.cardBorder}`,
    boxShadow: BRAND.cardShadow,
    flexWrap: "wrap",
  },
  toolbarTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 800,
    color: BRAND.ink,
    minWidth: 140,
  },
  toolbarRight: {
    display: "flex",
    alignItems: "center",
    gap: 18,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  modeSwitch: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: 4,
    borderRadius: 999,
    background: "rgba(124,58,237,0.07)",
    border: `1px solid ${BRAND.cardBorder}`,
  },
  modeButton: {
    minHeight: 36,
    padding: "0 16px",
    borderRadius: 999,
    border: "none",
    color: BRAND.inkSoft,
    fontSize: 13,
    fontWeight: 800,
    background: "transparent",
    whiteSpace: "nowrap",
  },
  modeButtonActive: {
    color: "#ffffff",
    background: GRADIENTS.primary,
    boxShadow: "0 8px 18px rgba(124,58,237,0.18)",
  },
  uploadError: { padding: "0 4px", color: "#db2777", fontSize: 14 },
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 2.6fr) minmax(260px, 1fr)",
    gap: 20,
    alignItems: "start",
  },
  leftColumn: { display: "flex", flexDirection: "column", gap: 16, minWidth: 0 },
  rightColumn: { display: "flex", flexDirection: "column", gap: 16, minWidth: 0 },
  settingsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  chordKeyCard: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
    alignItems: "center",
    padding: "10px 18px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.86)",
    border: `1px solid ${BRAND.cardBorder}`,
    boxShadow: "0 8px 20px rgba(124,58,237,0.08)",
    fontSize: 13,
    color: BRAND.ink,
  },
  graphPanel: {
    borderRadius: 20,
    background: "radial-gradient(circle at 18% 12%, rgba(232,148,255,0.18), transparent 26%), radial-gradient(circle at 80% 20%, rgba(148,185,255,0.22), transparent 28%), rgba(255,255,255,0.72)",
    border: `1px solid ${BRAND.cardBorder}`,
    boxShadow: BRAND.cardShadow,
    overflow: "hidden",
    height: 560,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  scoreGraphLabel: {
    position: "absolute",
    top: 18,
    left: 20,
    right: 20,
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "9px 14px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.82)",
    border: `1px solid ${BRAND.cardBorder}`,
    boxShadow: "0 8px 20px rgba(124,58,237,0.08)",
    color: BRAND.inkSoft,
    fontSize: 12,
    pointerEvents: "none",
  },
} satisfies Record<string, CSSProperties>;
