import type { CSSProperties } from "react";

export const styles = {
  bar: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: 80,
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    background: "rgba(255,255,255,0.8)",
    backdropFilter: "blur(10px)",
    zIndex: 1000,
    transition: "transform 0.4s ease-in-out",
  },
  barHidden: {
    transform: "translateY(-100%)",
  },
  logo: { display: "flex", alignItems: "center" },
  logoImg: { marginTop: "15%", width: 80, height: 80, objectFit: "contain" },
  right: { display: "flex", alignItems: "center" },
  nav: { display: "flex", alignItems: "center", gap: 40, marginRight: 52 },
  navLink: {
    position: "relative",
    fontSize: 19,
    fontWeight: 600,
    color: "#8e8ca3",
    textDecoration: "none",
    cursor: "pointer",
    background: "none",
    border: "none",
    fontFamily: "inherit",
    padding: "0 0 5px",
    transition: "color 0.3s",
  },
  hamburger: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: 28,
    height: 20,
    padding: 0,
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  hamburgerLine: {
    display: "block",
    width: "100%",
    height: 3,
    background: "#5c5a72",
    borderRadius: 3,
  },
} satisfies Record<string, CSSProperties>;
